- name: 📌 Verificar cambios en quiniela.json
  run: |
    if git diff --exit-code quiniela.json; then
      echo "No hay cambios en quiniela.json, no se subirá nada."
      exit 0
    fi

- name: 🚀 Subir cambios a GitHub
  run: |
    git add quiniela.json
    git commit -m "🤖 Actualización automática de quiniela.json"
    git push
